FROM ubuntu:lastest AS build

RUN apt-get update
Run apt-get install openjdk-17-jdk -y

COPY ..

RUN apt-get install maven -y
RUN mvn clean install

From onpenjdk:17-jdk-slim
EXPOSE 8080

COPY --from=build /target/todoList-1.0.0.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]